"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERROR_MESSAGES = exports.ERROR_CODES = void 0;
exports.ERROR_CODES = {
    INVALID_API_KEY: 'ELG_001',
    EXPIRED_API_KEY: 'ELG_002',
    MISSING_API_KEY: 'ELG_003',
    INVALID_JWT: 'ELG_004',
    INSUFFICIENT_PERMISSION: 'ELG_005',
    INVALID_BANK_CODE: 'ELG_020',
    INVALID_ACCOUNT_NUMBER: 'ELG_021',
    INVALID_CURRENCY: 'ELG_022',
    AMOUNT_TOO_LOW: 'ELG_023',
    AMOUNT_TOO_HIGH: 'ELG_024',
    DUPLICATE_REFERENCE: 'ELG_025',
    INVALID_PHONE_NUMBER: 'ELG_026',
    MISSING_REQUIRED_FIELD: 'ELG_027',
    INVALID_REQUEST_BODY: 'ELG_028',
    SANCTIONS_HIT: 'ELG_040',
    COMPLIANCE_CHECK_FAILED: 'ELG_041',
    KYC_REQUIRED: 'ELG_042',
    TRANSACTION_FLAGGED: 'ELG_043',
    RATE_UNAVAILABLE: 'ELG_060',
    RATE_EXPIRED: 'ELG_061',
    PSP_UNAVAILABLE: 'ELG_080',
    BANK_ACCOUNT_NOT_FOUND: 'ELG_081',
    BANK_ACCOUNT_RESTRICTED: 'ELG_082',
    INSUFFICIENT_PSP_FUNDS: 'ELG_083',
    TRANSFER_REJECTED: 'ELG_084',
    TRANSFER_TIMEOUT: 'ELG_085',
    PAYOUT_NOT_FOUND: 'ELG_100',
    PAYOUT_ALREADY_TERMINAL: 'ELG_101',
    PAYOUT_NOT_RETRYABLE: 'ELG_102',
    WEBHOOK_URL_INVALID: 'ELG_120',
    WEBHOOK_NOT_FOUND: 'ELG_121',
    WEBHOOK_LIMIT_REACHED: 'ELG_122',
    PARTNER_NOT_FOUND: 'ELG_140',
    PARTNER_SUSPENDED: 'ELG_141',
    PARTNER_ALREADY_EXISTS: 'ELG_142',
    INTERNAL_SERVER_ERROR: 'ELG_900',
    SERVICE_UNAVAILABLE: 'ELG_901',
    RATE_LIMIT_EXCEEDED: 'ELG_902',
};
exports.ERROR_MESSAGES = {
    [exports.ERROR_CODES.INVALID_API_KEY]: 'The provided API key is invalid or has been revoked.',
    [exports.ERROR_CODES.EXPIRED_API_KEY]: 'The API key has expired. Please generate a new one.',
    [exports.ERROR_CODES.MISSING_API_KEY]: 'Authorization header is required.',
    [exports.ERROR_CODES.INVALID_JWT]: 'Session token is invalid or has expired.',
    [exports.ERROR_CODES.INSUFFICIENT_PERMISSION]: 'You do not have permission to perform this action.',
    [exports.ERROR_CODES.INVALID_BANK_CODE]: 'The bank code provided is not a valid CBN-registered bank.',
    [exports.ERROR_CODES.INVALID_ACCOUNT_NUMBER]: 'Account number must be exactly 10 digits (NUBAN format).',
    [exports.ERROR_CODES.INVALID_CURRENCY]: 'Currency not supported. Supported: GBP, USD, EUR, CAD.',
    [exports.ERROR_CODES.AMOUNT_TOO_LOW]: 'Transfer amount is below the minimum allowed.',
    [exports.ERROR_CODES.AMOUNT_TOO_HIGH]: 'Transfer amount exceeds the maximum allowed.',
    [exports.ERROR_CODES.DUPLICATE_REFERENCE]: 'A payout with this partnerReference already exists.',
    [exports.ERROR_CODES.INVALID_PHONE_NUMBER]: 'Phone number must be a valid Nigerian mobile number.',
    [exports.ERROR_CODES.MISSING_REQUIRED_FIELD]: 'One or more required fields are missing.',
    [exports.ERROR_CODES.INVALID_REQUEST_BODY]: 'Request body is malformed or contains invalid types.',
    [exports.ERROR_CODES.SANCTIONS_HIT]: 'Recipient matched a sanctions screening list. Payout flagged.',
    [exports.ERROR_CODES.COMPLIANCE_CHECK_FAILED]: 'Compliance check could not be completed. Please retry.',
    [exports.ERROR_CODES.KYC_REQUIRED]: 'Partner KYC verification is required before processing payouts.',
    [exports.ERROR_CODES.TRANSACTION_FLAGGED]: 'Transaction has been flagged for manual review.',
    [exports.ERROR_CODES.RATE_UNAVAILABLE]: 'Exchange rate is temporarily unavailable. Please retry.',
    [exports.ERROR_CODES.RATE_EXPIRED]: 'The quoted exchange rate has expired. Fetch a new rate.',
    [exports.ERROR_CODES.PSP_UNAVAILABLE]: 'Payment processing is temporarily unavailable. Please retry.',
    [exports.ERROR_CODES.BANK_ACCOUNT_NOT_FOUND]: 'Recipient account number was not found at the specified bank.',
    [exports.ERROR_CODES.BANK_ACCOUNT_RESTRICTED]: 'Recipient account is restricted and cannot receive funds.',
    [exports.ERROR_CODES.INSUFFICIENT_PSP_FUNDS]: 'Platform wallet requires topping up. Contact support.',
    [exports.ERROR_CODES.TRANSFER_REJECTED]: 'Bank rejected the transfer. Check recipient account details.',
    [exports.ERROR_CODES.TRANSFER_TIMEOUT]: 'Bank transfer timed out. Check status before retrying.',
    [exports.ERROR_CODES.PAYOUT_NOT_FOUND]: 'No payout found with the provided ID.',
    [exports.ERROR_CODES.PAYOUT_ALREADY_TERMINAL]: 'Payout is in a terminal state and cannot be modified.',
    [exports.ERROR_CODES.PAYOUT_NOT_RETRYABLE]: 'Payout status does not allow retry.',
    [exports.ERROR_CODES.WEBHOOK_URL_INVALID]: 'Webhook URL is not reachable or has an invalid format.',
    [exports.ERROR_CODES.WEBHOOK_NOT_FOUND]: 'No webhook found with the provided ID.',
    [exports.ERROR_CODES.WEBHOOK_LIMIT_REACHED]: 'Maximum number of webhooks per partner reached.',
    [exports.ERROR_CODES.PARTNER_NOT_FOUND]: 'No partner found with the provided ID.',
    [exports.ERROR_CODES.PARTNER_SUSPENDED]: 'Partner account is suspended. Contact support.',
    [exports.ERROR_CODES.PARTNER_ALREADY_EXISTS]: 'A partner with this email already exists.',
    [exports.ERROR_CODES.INTERNAL_SERVER_ERROR]: 'An unexpected error occurred. Please retry or contact support.',
    [exports.ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service is temporarily unavailable. Please retry shortly.',
    [exports.ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Too many requests. Please slow down and retry.',
};
//# sourceMappingURL=error-codes.js.map