// packages/constants/src/error-codes.d.ts
export declare const ERROR_CODES: {
    readonly INVALID_API_KEY: "ELG_001";
    readonly EXPIRED_API_KEY: "ELG_002";
    readonly MISSING_API_KEY: "ELG_003";
    readonly INVALID_JWT: "ELG_004";
    readonly INSUFFICIENT_PERMISSION: "ELG_005";
    readonly INVALID_BANK_CODE: "ELG_020";
    readonly INVALID_ACCOUNT_NUMBER: "ELG_021";
    readonly INVALID_CURRENCY: "ELG_022";
    readonly AMOUNT_TOO_LOW: "ELG_023";
    readonly AMOUNT_TOO_HIGH: "ELG_024";
    readonly DUPLICATE_REFERENCE: "ELG_025";
    readonly INVALID_PHONE_NUMBER: "ELG_026";
    readonly MISSING_REQUIRED_FIELD: "ELG_027";
    readonly INVALID_REQUEST_BODY: "ELG_028";
    readonly SANCTIONS_HIT: "ELG_040";
    readonly COMPLIANCE_CHECK_FAILED: "ELG_041";
    readonly KYC_REQUIRED: "ELG_042";
    readonly TRANSACTION_FLAGGED: "ELG_043";
    readonly RATE_UNAVAILABLE: "ELG_060";
    readonly RATE_EXPIRED: "ELG_061";
    readonly PSP_UNAVAILABLE: "ELG_080";
    readonly BANK_ACCOUNT_NOT_FOUND: "ELG_081";
    readonly BANK_ACCOUNT_RESTRICTED: "ELG_082";
    readonly INSUFFICIENT_PSP_FUNDS: "ELG_083";
    readonly TRANSFER_REJECTED: "ELG_084";
    readonly TRANSFER_TIMEOUT: "ELG_085";
    readonly PAYOUT_NOT_FOUND: "ELG_100";
    readonly PAYOUT_ALREADY_TERMINAL: "ELG_101";
    readonly PAYOUT_NOT_RETRYABLE: "ELG_102";
    readonly WEBHOOK_URL_INVALID: "ELG_120";
    readonly WEBHOOK_NOT_FOUND: "ELG_121";
    readonly WEBHOOK_LIMIT_REACHED: "ELG_122";
    readonly PARTNER_NOT_FOUND: "ELG_140";
    readonly PARTNER_SUSPENDED: "ELG_141";
    readonly PARTNER_ALREADY_EXISTS: "ELG_142";
    readonly INTERNAL_SERVER_ERROR: "ELG_900";
    readonly SERVICE_UNAVAILABLE: "ELG_901";
    readonly RATE_LIMIT_EXCEEDED: "ELG_902";
};
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
export declare const ERROR_MESSAGES: Record<ErrorCode, string>;
//# sourceMappingURL=error-codes.d.ts.map